apiVersion: v1
kind: Service
metadata:
  name: ndt-service
  namespace: default
spec:
  selector:
    workload: ndt
  type: LoadBalancer
  # The "local" traffic policy preserves clientIP and routes to a service on the same node.
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
