- name: ifHCInOctets
  description: Ingress octets.
  oidStub: .1.3.6.1.2.1.31.1.1.1.6
  mlabUplinkName: switch.octets.uplink.rx
  mlabMachineName: switch.octets.local.rx
- name: ifHCOutOctets
  description: Egress octets.
  oidStub: .1.3.6.1.2.1.31.1.1.1.10
  mlabUplinkName: switch.octets.uplink.tx
  mlabMachineName: switch.octets.local.tx
- name: ifHCInUcastPkts
  description: Ingress unicast packets.
  oidStub: .1.3.6.1.2.1.31.1.1.1.7
  mlabUplinkName: switch.unicast.uplink.rx
  mlabMachineName: switch.unicast.local.rx
- name: ifHCOutUcastPkts
  description: Egress unicast packets.
  oidStub: .1.3.6.1.2.1.31.1.1.1.11
  mlabUplinkName: switch.unicast.uplink.tx
  mlabMachineName: switch.unicast.local.tx
- name: ifInErrors
  description: Ingress errors.
  oidStub: .1.3.6.1.2.1.2.2.1.14
  mlabUplinkName: switch.errors.uplink.rx
  mlabMachineName: switch.errors.local.rx
- name: ifOutErrors
  description: Egress errors.
  oidStub: .1.3.6.1.2.1.2.2.1.20
  mlabUplinkName: switch.errors.uplink.tx
  mlabMachineName: switch.errors.local.tx
- name: ifInDiscards
  description: Ingress discards.
  oidStub: .1.3.6.1.2.1.2.2.1.13
  mlabUplinkName: switch.discards.uplink.rx
  mlabMachineName: switch.discards.local.rx
- name: ifOutDiscards
  description: Egress discards.
  oidStub: .1.3.6.1.2.1.2.2.1.19
  mlabUplinkName: switch.discards.uplink.tx
  mlabMachineName: switch.discards.local.tx
- name: ifHCInBroadcastPkts
  description: Ingress broadcast packets.
  oidStub: .1.3.6.1.2.1.31.1.1.1.9
  mlabUplinkName: switch.broadcast.uplink.rx
  mlabMachineName: switch.broadcast.local.rx
- name: ifHCOutBroadcastPkts
  description: Egress broadcast packets.
  oidStub: .1.3.6.1.2.1.31.1.1.1.13
  mlabUplinkName: switch.broadcast.uplink.tx
  mlabMachineName: switch.broadcast.local.tx
