steps:
# Create the configs
- name: gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif
  dir: '/workspace/manage-cluster'
  args: [
    '/workspace/manage-cluster/create_k8s_configs.sh $PROJECT_ID'
  ]

# Push the configs.
- name: gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif
  dir: '/workspace/manage-cluster'
  args: [
    '/workspace/manage-cluster/apply_k8s_configs.sh $PROJECT_ID'
  ]
