#!/bin/bash

# If the pod has index\d+ in its name, then use the number after index to
# determine what extra external IP to assign the pod.  Otherwise, exit
# unsuccessfully.

# This shell script should be replaced with go.

cat - > /dev/null
if echo "${CNI_ARGS}" | sed -e 's/.*K8S_POD_NAME=//' -e 's/;.*//' | grep -q 'index[0-9][0-9]*'; then
  # Read the index out of the name of the POD
  INDEX=$(echo "${CNI_ARGS}" | sed -e 's/.*K8S_POD_NAME=//' -e 's/;.*//' -e 's/.*index//' -e 's/[^0-9].*//')
  ROUTES='{ "dst": "0.0.0.0/0" }'
else
  # No IP is assignable.
  exit 1
fi
IPV4_ARGS=$(cat /proc/cmdline | sed -e 's/.*epoxy.ipv4=//' -e 's# .*##' -e 's/,/ /g')
IP=$(echo "${IPV4_ARGS}" | awk '{print $1}' | sed -e 's#/.*##')
GATEWAY=$(echo "${IPV4_ARGS}" | awk '{print $2}')
DNS1=$(echo "${IPV4_ARGS}" | awk '{print $3}')
DNS2=$(echo "${IPV4_ARGS}" | awk '{print $4}')
NEW_IP=$(echo "${IP}" | sed -e 's/\./ /g' | awk "{print \$1 \".\" \$2 \".\" \$3 \".\" (\$4+${INDEX})}")
cat <<EOF
{
  "cniVersion": "0.2.0",
  "ip4": {
      "ip": "${NEW_IP}/26",
      "gateway": "${GATEWAY}",
      "routes": [ ${ROUTES} ]
  },
  "dns": {
      "nameservers": [
          "${DNS1}",
          "${DNS2}"
      ]
  }
}
EOF
