---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: flannel-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "flannel",
    "delegate": {
       "hairpinMode": true,
       "isDefaultGateway": true
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-1-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-1",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 1
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-2-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-2",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 2
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-4-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-4",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 4
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-5-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-5",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 5
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-6-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-6,
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 6
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-7-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-7",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 7
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-8-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-8",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 8
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-9-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-9",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 9
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-10-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-10",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 10
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-11-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-11",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 11
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-12-conf
spec:
  config: '{
    "cniVersion": "0.2.0",
    "name": "ipvlan-index-12",
    "type": "ipvlan",
    "master": "eth0",
    "ipam": {
      "type": "index2ip",
      "index": 12
    }
  }'
