bpf:
  autoMount:
    enabled: false
cni:
  exclusive: false
endpointRoutes:
  enabled: true
hubble:
  relay:
    enabled: true
    nodeSelector:
      run: prometheus-server
ipam:
  mode: kubernetes
k8sServiceHost: api-platform-cluster.mlab-sandbox.measurementlab.net
k8sServicePort: 6443
kubeProxyReplacement: true
MTU: 1460
routingMode: native

