bpf:
  autoMount:
    enabled: false
cni:
  exclusive: false
debug:
  enabled: true
envoy:
  enabled: false
ipam:
  mode: kubernetes
k8sServiceHost: 172.25.0.1
k8sServicePort: 6443
kubeProxyReplacement: true

