configuration:
  lockTtl: 4h
  period: 1h
  rebootSentinel: /run/mlab-reboot
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/scheme: http
podLabels:
  workload: kured
tolerations:
- key: lame-duck
  operator: Exists
  effect: NoSchedule
